export const GET_ALL_QA_REQUEST = "GET_ALL_QA_REQUEST";
export const GET_ALL_QA_SUCCESS = "GET_ALL_QA_SUCCESS";
export const GET_ALL_QA_FAILURE = "GET_ALL_QA_FAILURE";

export const ADD_QA_REQUEST = "ADD_QA_REQUEST";
export const ADD_QA_SUCCESS = "ADD_QA_SUCCESS";
export const ADD_QA_FAILURE = "ADD_QA_FAILURE";

export const EDIT_QA_REQUEST = "EDIT_QA_REQUEST";
export const EDIT_QA_SUCCESS = "EDIT_QA_SUCCESS";
export const EDIT_QA_FAILURE = "EDIT_QA_FAILURE";

export const DELETE_QA_REQUEST = "DELETE_QA_REQUEST";
export const DELETE_QA_SUCCESS = "DELETE_QA_SUCCESS";
export const DELETE_QA_FAILURE = "DELETE_QA_FAILURE";

export const DELETE_ALL_QA_REQUEST = "DELETE_ALL_QA_REQUEST";
export const DELETE_ALL_QA_SUCCESS = "DELETE_ALL_QA_SUCCESS";
export const DELETE_ALL_QA_FAILURE = "DELETE_ALL_QA_FAILURE";
